<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<title>loginpage</title>
<link rel="stylesheet" href="css/style.css">
<link href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css" integrity="sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p" crossorigin="anonymous"/>


  <link href="https://fonts.googleapis.com/css?family=Karla:400,700&display=swap" rel="stylesheet">
  <link rel="stylesheet" href="https://cdn.materialdesignicons.com/4.8.95/css/materialdesignicons.min.css">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">

<link rel="stylesheet" href="css/style.css">
</head>
<body>
   
    <?php  include 'include/header1.php';?>

<div class="content">
<div class="container">
<div class="row">
<div class="col-md-6">
<img src="images/undraw_remotely_2j6y.svg" alt="Image" class="img-fluid">
</div>
<div class="col-md-6 contents">
<div class="row justify-content-center">
<div class="col-md-8">
<div class="mb-4">
<h3>Sign In</h3>
<p class="mb-4">Lorem ipsum dolor sit amet elit. Sapiente sit aut eos consectetur adipisicing.</p>
</div>
<form action="#" method="post">
<div class="form-group first">
<label for="username">Username</label>
<input type="text" class="form-control" id="username">
</div>
<div class="form-group last mb-4">
<label for="password">Password</label>
<input type="password" class="form-control" id="password">
</div>
<div class="d-flex mb-5 align-items-center">
<label class="control control--checkbox mb-0"><span class="caption">Remember me</span>
<input type="checkbox" checked />
<div class="control__indicator"></div>
</label>
<span class="ml-auto"><a href="#" class="forgot-pass">Forgot Password</a></span>
</div>
<input type="submit" value="Log In" class="btn btn-block btn-primary">
<span class="d-block text-left my-4 text-muted">&mdash; or login with &mdash;</span>
<div class="social-login">
<a href="#" class="facebook">
<span class="icon-facebook mr-3"></span>
</a>
<a href="#" class="twitter">
<span class="icon-twitter mr-3"></span>
</a>
<a href="#" class="google">
<span class="icon-google mr-3"></span>
</a>
</div>
</form>
</div>
</div>
</div>
</div>
</div>
</div>
<script src="js/jquery-3.3.1.min.js"></script>
<script src="js/popper.min.js%2bbootstrap.min.js%2bmain.js.pagespeed.jc.9rL6_qf-nt.js"></script><script>eval(mod_pagespeed_$$cYUBAGVu);</script>
<script>eval(mod_pagespeed_MR4O_w3mta);</script>
<script>eval(mod_pagespeed_DPOuBfjpPE);</script>
<script defer src="../../../../static.cloudflareinsights.com/beacon.min.js" data-cf-beacon='{"rayId":"6733c667ce0a0f00","token":"cd0b4b3a733644fc843ef0b185f98241","version":"2021.7.0","si":10}'></script>

</body>
</html>